### ISSUE TITLE
Debug LODs in editor

### ISSUE THREAD

**Issue by okla** [Calinou/godot-lod#7] opened 2022-05-08 11:05 UTC
Is it possible to view LOD changes in editor view or is it supposed to work in render only? I set up a scene with LODSpatial and a camera, but when I move the camera, LODs do not change in the camera preview viewport.

**Comment by Calinou** [comment] 2022-05-08 16:06
Duplicate of https://github.com/godot-extended-libraries/godot-lod/issues/6.

Making LODs effective within the editor would introduce unnecessary VCS diffs when saving scenes, so a different solution is needed.

**Closed as completed by Calinou** 2022-05-08 16:06 UTC
Labels: enhancement, invalid

**Comment by okla** [comment] 2022-05-09 09:28
@Calinou Maybe there is a way to modify a scene in-memory, without saving the changes to the scene file? Mark these changes as "ephemeral" or something. Probably this would be helpful to visualize Remote changes as well.

**Comment by Calinou** [comment] 2022-05-09 12:09
> Maybe there is a way to modify a scene in-memory, without saving the changes to the scene file? Mark these changes as "ephemeral" or something.

Godot can only do this if you *add* new nodes using a tool script (and don't set an owner for them), not if you modify existing nodes' properties (`visible` in this case).
